### ISSUE TITLE
Add to composer

### ISSUE THREAD

**Issue by haskellcamargo** [haskellcamargo/php-maybe-monad#1]
Add project to composer.

**Comment by reinaldorauch** [comment]
Do you have an packagist account?

**Comment by haskellcamargo** [comment]
I didn't. I created it just now. Look for `haskellcamargo`.
It is up and running! https://packagist.org/packages/haskellcamargo/php-maybe-monad
Thanks!

**Comment by reinaldorauch** [comment]
:+1:
